### PR TITLE
fix: truncate long object name

### PR DESCRIPTION
**Pull request by catouberos**
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced layout for the Transaction Details page, improving the presentation of transaction information.
	- Improved text handling for file names with better spacing and alignment.

- **Bug Fixes**
	- Maintained robust error handling during data fetching to ensure reliability.

### CODE REVIEW

**Review by vhpx — APPROVED** [review]
LGTM! thanks @catouberos.

**Comment by vhpx** [comment]
image

The name issue still overflows on mobile devices. Please address this issue as well, @catouberos.

**Review by vhpx — CHANGES_REQUESTED** [review]
Please add overflow handler for mobile devices as well.

**Comment by catouberos** [comment]
fixed in latest commit

image

**Pull request merged**
